runtime: python311

# App Engine configuration
entrypoint: gunicorn -b :$PORT wsgi:application

env_variables:
  OPENWEATHER_API_KEY: "YOUR_NEW_OPENWEATHERMAP_API_KEY_HERE"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource limits
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health check configuration
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Skip files are handled by .gcloudignore file
